"""Contrato de repositorio — el service layer (service.py) depende SOLO de esto, nunca de
una implementación concreta. Dos implementaciones (ver ../repositories/): InMemoryRepository
(para tests, determinista, sin red) y CosmosRepository (producción, la fuente de verdad
real — ver docs/decisions/004-agente-ia-mcp-cosmosdb.md, la decisión es que Cosmos DB es la
única fuente de verdad, no una réplica)."""

from __future__ import annotations

from typing import Protocol, runtime_checkable

from .types import Material, Order, Product, ProductVariant, StockMovement


@runtime_checkable
class ErpRepository(Protocol):
    def list_products(self) -> list[Product]: ...
    def get_product(self, product_id: str) -> Product | None: ...
    def save_product(self, product: Product) -> None: ...

    def list_variants(self, product_id: str | None = None) -> list[ProductVariant]: ...
    def get_variant(self, variant_id: str) -> ProductVariant | None: ...
    def save_variant(self, variant: ProductVariant) -> None: ...
    def set_variant_stock(self, variant_id: str, new_stock: int) -> None: ...

    def list_materials(self) -> list[Material]: ...
    def get_material(self, material_id: str) -> Material | None: ...
    def set_material_stock(self, material_id: str, new_stock: int) -> None: ...

    def list_orders(self) -> list[Order]: ...
    def get_order(self, order_id: str) -> Order | None: ...
    def save_order(self, order: Order) -> None: ...
    def count_orders(self) -> int: ...

    def add_movement(self, movement: StockMovement) -> None: ...
    def list_movements(self, target_id: str) -> list[StockMovement]: ...
